name: Automate Release

on:
  workflow_dispatch: # Manually trigger this workflow
    inputs:
      version: # Specify the new version to release
        description: "Enter the new version (e.g., 1.0.1)"
        required: true
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
        contents: write # Needed for creating branches and releases
        actions: read   # For triggering other workflows
    steps:
      - name: Checkout latest branch
        uses: actions/checkout@v3
        with:
          ref: latest # Start from the "latest" branch

#      - name: Create release branch
#        id: create_branch
#        run: |
#          NEW_BRANCH="release-${{ github.event.inputs.version }}"
#          git checkout -b $NEW_BRANCH
#          git push origin $NEW_BRANCH
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ github.event.inputs.version }}'
          sha: '${{ github.event.pull_request.head.sha }}'

  trigger-build:
    needs: create-release-branch
    runs-on: ubuntu-latest
    permissions:
        actions: read   # For triggering other workflows
        # permissions that needs to be inherited by the other workflow
        contents: read
        packages: write
        attestations: write
        id-token: write
    if: ${{ needs.create-release-branch.result == 'success' }}
    steps:
      - name: ref check
        run: |
          echo release-${{ github.event.inputs.version }}
          echo ${{ github.repository }}
          echo "2"
          
      - name: Trigger Build Docker Image Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: pracan/docker-like-name-generator
          workflow: build-container.yml # Replace with the name of your Docker build workflow
          ref: release-${{ github.event.inputs.version }}
          #token: ${{ secrets.GITHUB_TOKEN }}

  create-github-release:
    needs: trigger-build
    runs-on: ubuntu-latest
    permissions:
        contents: write # Needed for creating branches and releases
    if: ${{ needs.trigger-build.result == 'success' }}
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: |
            🎉 **Release v${{ github.event.inputs.version }}** 🎉
            
            This release includes the following updates:
            
            - [Add your changelog items here!]
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
